# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aicr < Formula
  desc "Tooling for deploying optimized, validated, and reproducible GPU-accelerated AI runtime in Kubernetes."
  homepage "https://github.com/NVIDIA/aicr"
  version "0.20.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.20.0/aicr_0.20.0_darwin_amd64.tar.gz"
      sha256 "3805fcc5e44f4a2b6020bcb395adcb99887ae1617484067682d414ca07aebcaa"

      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
        generate_completions_from_executable(bin/"aicr", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.20.0/aicr_0.20.0_darwin_arm64.tar.gz"
      sha256 "0e1b735f91383f0ba130aedf2b83299d0255587474e80dabf0392e194460a846"

      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
        generate_completions_from_executable(bin/"aicr", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.20.0/aicr_0.20.0_linux_amd64.tar.gz"
      sha256 "a80a7ed1ad7474434c929efbea77223b0eb156f901569319698e9bdb9e1126f9"
      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
        generate_completions_from_executable(bin/"aicr", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.20.0/aicr_0.20.0_linux_arm64.tar.gz"
      sha256 "f8353a56ff430714818879c8b4c4de057c0e3cea11beb34f45e4753db8f300f5"
      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
        generate_completions_from_executable(bin/"aicr", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To verify supply-chain provenance (requires cosign):

        cosign verify-blob-attestation \\
          --bundle #{opt_bin}/aicr-attestation.sigstore.json \\
          --type https://slsa.dev/provenance/v1 \\
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \\
          --certificate-identity-regexp "https://github.com/NVIDIA/aicr/.github/workflows/on-tag\\.yaml@refs/tags/.*" \\
          #{opt_bin}/aicr

      To update the trust root for bundle attestation:

        aicr trust update
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aicr version")
  end
end
