# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aicr < Formula
  desc "Tooling for deploying optimized, validated, and reproducible GPU-accelerated AI runtime in Kubernetes."
  homepage "https://github.com/NVIDIA/aicr"
  version "0.10.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.10.13/aicr_0.10.13_darwin_amd64.tar.gz"
      sha256 "9fb05b109fe7a2185fe12ed98e2b1eacffdbf52f9fe315327797af3fd8b4b155"

      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.10.13/aicr_0.10.13_darwin_arm64.tar.gz"
      sha256 "9aa4b630cdc75ef8e83fd6aad13fbcf539937b6b13d87df4591a3cfe17de5b59"

      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.10.13/aicr_0.10.13_linux_amd64.tar.gz"
      sha256 "19d66dca0811fed31d31da87d597ace019e08bfaa17c3bc23533fb21ae6e31cc"
      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NVIDIA/aicr/releases/download/v0.10.13/aicr_0.10.13_linux_arm64.tar.gz"
      sha256 "3346350889f53d190cbee785873b5a816f16ee0dd48fe22f9f0302393c758e1f"
      define_method(:install) do
        bin.install "aicr"
        bin.install "aicr-attestation.sigstore.json" if File.exist? "aicr-attestation.sigstore.json"
      end
    end
  end

  def caveats
    <<~EOS
      To verify supply-chain provenance (requires cosign):

        cosign verify-blob-attestation \
          --bundle #{opt_bin}/aicr-attestation.sigstore.json \
          --type https://slsa.dev/provenance/v1 \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity-regexp "https://github.com/NVIDIA/aicr/.github/workflows/on-tag\\.yaml@refs/tags/.*" \
          #{opt_bin}/aicr

      To update the trust root for bundle attestation:

        aicr trust update
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aicr version")
  end
end
